-- Crisis Aware keyword suggestions — add BrandProfile.suggestedCrisisKeywords,
-- a JSON list of {keyword, category, dismissed} generated by Brand AI and
-- reviewed on the Brand AI page before becoming a real Guardrail row.
-- Additive, idempotent.
ALTER TABLE "BrandProfile" ADD COLUMN IF NOT EXISTS "suggestedCrisisKeywords" JSONB;
